#### Составьте каноническое уравнение эллипсоида, проходящего через три точки A,B,C

Каноническое уравнение эллипсоида в прямоугольной декартовой системе координат имеет вид:
{x^2}/{a^2}+{y^2}/{b^2}+{z^2}/{c^2}=1 

Задача состоит в определении параметров a^2, b^2 и c^2.

In [1]:
import numpy as np

In [5]:
a = np.matrix([[3,0,3],[6,1/4,0],[1,1/3,1]])
b = np.matrix("1;1;1")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
x

matrix([[0.08333333],
        [2.        ],
        [0.25      ]])

In [8]:
result=1/x
result

matrix([[12. ],
        [ 0.5],
        [ 4. ]])

In [10]:
y = np.linalg.solve(a, b)
resultY=1/y
resultY

matrix([[12. ],
        [ 0.5],
        [ 4. ]])